[tools]
node = "22"

[tasks.update]
run = [
    "npx npm-check-updates --target minor -u --cooldown 3",
    "npm install",
    "npm audit",
]

[tasks.app]
run = "npx vite --config ./.config/vite.config.ts"
