name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: "チェックアウト"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: "mise をセットアップ"
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5  # v3.5.1

      - name: "依存関係をインストール"
        run: |
          npm install
          npx playwright install chromium --with-deps

      - name: "テスト"
        run: mise run test
        working-directory: "packages/soseki"

      - name: "ビルド"
        run: mise run build
        working-directory: "packages/soseki"

  # verify-npm-token:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "チェックアウト"
  #       uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

  #     - name: "mise をセットアップ"
  #       uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5  # v3.5.1

  #     - name: "NPM トークンの検証"
  #       run: |
  #         echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
  #         USER=$(npm whoami)
  #         echo "✅ NPM token is valid. Logged in as: $USER"
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
