name: "パッケージを公開"
run-name: "v${{ github.event.inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "バージョン (e.g., 1.2.3)"
        required: true

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
        contents: write
        id-token: write
    steps:
      - name: "チェックアウト"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: "Git の設定"
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: "mise をセットアップ"
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5  # v3.5.1

      - name: "バージョン確認"
        run: |
          if npm view "soseki@${{ github.event.inputs.version }}" version >/dev/null 2>&1; then
            echo "Error: そのバージョンはすでに存在しています。" >&2
            exit 1
          fi

      - name: "依存関係をインストール"
        run: npm ci

      - name: "ビルド"
        run: mise run build
        working-directory: "packages/soseki"

      - name: "バージョンを更新"
        run: npm version '${{ github.event.inputs.version }}'
        working-directory: "packages/soseki"

      - name: "すでにタグがあれば削除"
        run: |
          if git rev-parse "refs/tags/v${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            git tag -d v${{ github.event.inputs.version }}
            git push origin --delete v${{ github.event.inputs.version }} || true
          fi
        working-directory: "packages/soseki"

      - name: "タグ打ち"
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: "packages/soseki"

      - name: "公開"
        run: |
          echo 'registry=https://registry.npmjs.org' >.npmrc
          npm publish --access public
        working-directory: "packages/soseki"
